name: Build Fork PR

# read-only
# no access to secrets
on:
  pull_request:

# Run a single job at a time
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Fork PR
    uses: tlylt/markbind-reusable-workflows/.github/workflows/fork-build.yml@main
    with:
      version: master
