name: Build Fork PR

# read-only
# no access to secrets
on:
  pull_request:

# cancel multiple runs at the same time, can be removed if you don't need it
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Fork PR
    uses: tlylt/markbind-reusable-workflows/.github/workflows/fork-build.yml@main
    with:
      version: "3.1.1"
      baseUrl: ""
