name: Preview Fork PR

on:
  workflow_run:
    workflows: ["Build Fork PR"]
    types: [completed]

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploying to surge
    uses: tlylt/markbind-reusable-workflows/.github/workflows/fork-preview.yml@main
    with:
      baseUrl: 'test-md'
    secrets:
      token: ${{ secrets.SURGE_TOKEN }}